use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::Mutex;

use serde::{Deserialize, Serialize};
use tauri::{Manager, WebviewUrl, WebviewWindowBuilder};

/// Where the game window points. Everything — client bundle, GRF assets and the
/// game socket — is served from this single origin by RemoteClient-JS.
const GAME_URL: &str = "http://127.0.0.1:3338/play.html";
const HEALTH_URL: &str = "http://127.0.0.1:3338/api/health";

/// Rates the Settings pane exposes. Values are multipliers in percent, matching
/// rAthena's own units (100 = 1x), so they can be written straight into
/// `conf/import/battle_conf.txt` without translation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Settings {
    pub base_exp_rate: u32,
    pub job_exp_rate: u32,
    pub quest_exp_rate: u32,
    pub item_rate_common: u32,
    pub item_rate_equip: u32,
    pub item_rate_card: u32,
    pub zeny_rate: u32,
    pub atcommand_enabled: bool,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            base_exp_rate: 100,
            job_exp_rate: 100,
            quest_exp_rate: 100,
            item_rate_common: 100,
            item_rate_equip: 100,
            item_rate_card: 100,
            zeny_rate: 100,
            atcommand_enabled: true,
        }
    }
}

impl Settings {
    /// Render to rAthena's import override file. Upstream `conf/battle/*.conf`
    /// is never touched; `conf/import/battle_conf.txt` is read last and wins.
    fn to_battle_conf(&self) -> String {
        format!(
            "// Generated by RagnarokMac. Edits here are overwritten.\n\
             base_exp_rate: {}\n\
             job_exp_rate: {}\n\
             quest_exp_rate: {}\n\
             item_rate_common: {}\n\
             item_rate_common_boss: {}\n\
             item_rate_equip: {}\n\
             item_rate_equip_boss: {}\n\
             item_rate_card: {}\n\
             item_rate_card_boss: {}\n\
             item_rate_heal: {}\n\
             item_rate_use: {}\n\
             zeny_rate: {}\n\
             atcommand_max_level: {}\n",
            self.base_exp_rate,
            self.job_exp_rate,
            self.quest_exp_rate,
            self.item_rate_common,
            self.item_rate_common,
            self.item_rate_equip,
            self.item_rate_equip,
            self.item_rate_card,
            self.item_rate_card,
            self.item_rate_common,
            self.item_rate_common,
            self.zeny_rate,
            if self.atcommand_enabled { 99 } else { 100 },
        )
    }
}

#[derive(Default)]
struct AppState {
    assets: Mutex<Option<Child>>,
}

/// Repository root. In dev this is two levels up from `src-tauri`; in a bundled
/// .app the resources are copied alongside the binary.
fn project_root(app: &tauri::AppHandle) -> PathBuf {
    if let Ok(dir) = std::env::var("RAGNAROKMAC_ROOT") {
        return PathBuf::from(dir);
    }
    if let Ok(res) = app.path().resource_dir() {
        if res.join("scripts/stack.sh").exists() {
            return res;
        }
    }
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_default()
}

fn run_stack(app: &tauri::AppHandle, arg: &str) -> Result<String, String> {
    let root = project_root(app);
    let out = Command::new("bash")
        .arg(root.join("scripts/stack.sh"))
        .arg(arg)
        .current_dir(&root)
        .output()
        .map_err(|e| format!("failed to run stack.sh: {e}"))?;
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    if out.status.success() {
        Ok(stdout)
    } else {
        Err(format!(
            "{stdout}{}",
            String::from_utf8_lossy(&out.stderr)
        ))
    }
}

#[tauri::command]
fn stack_status(app: tauri::AppHandle) -> Result<String, String> {
    run_stack(&app, "status")
}

#[tauri::command]
fn stack_up(app: tauri::AppHandle) -> Result<String, String> {
    run_stack(&app, "up")
}

#[tauri::command]
fn stack_down(app: tauri::AppHandle) -> Result<String, String> {
    run_stack(&app, "down")
}

/// True once the RemoteClient-JS unified server answers its health endpoint.
#[tauri::command]
fn assets_ready() -> bool {
    Command::new("curl")
        .args(["-sf", "-m", "2", "-o", "/dev/null", HEALTH_URL])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

#[tauri::command]
fn assets_start(app: tauri::AppHandle, state: tauri::State<'_, AppState>) -> Result<(), String> {
    if assets_ready() {
        return Ok(());
    }
    let dir = project_root(&app).join("vendor/roBrowserLegacy-RemoteClient-JS");
    let child = Command::new("node")
        .arg("index.js")
        .current_dir(&dir)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| format!("failed to start asset server: {e}"))?;
    *state.assets.lock().unwrap() = Some(child);
    Ok(())
}

#[tauri::command]
fn assets_stop(state: tauri::State<'_, AppState>) {
    if let Some(mut child) = state.assets.lock().unwrap().take() {
        let _ = child.kill();
    }
}

#[tauri::command]
fn get_settings(app: tauri::AppHandle) -> Settings {
    let path = project_root(&app).join(".ragnarokmac/settings.json");
    std::fs::read_to_string(path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default()
}

/// Persist the rates and re-render the rAthena override file. The map server is
/// restarted because several of these are only read at map-server startup.
#[tauri::command]
fn save_settings(app: tauri::AppHandle, settings: Settings) -> Result<String, String> {
    let root = project_root(&app);
    let state_dir = root.join(".ragnarokmac");
    std::fs::create_dir_all(state_dir.join("conf")).map_err(|e| e.to_string())?;
    std::fs::write(
        state_dir.join("settings.json"),
        serde_json::to_string_pretty(&settings).map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;
    std::fs::write(
        state_dir.join("conf/battle_conf.txt"),
        settings.to_battle_conf(),
    )
    .map_err(|e| e.to_string())?;
    run_stack(&app, "up")
}

#[tauri::command]
fn open_game(app: tauri::AppHandle) -> Result<(), String> {
    if let Some(win) = app.get_webview_window("game") {
        let _ = win.set_focus();
        return Ok(());
    }
    let url = GAME_URL.parse().map_err(|_| "bad game url".to_string())?;
    WebviewWindowBuilder::new(&app, "game", WebviewUrl::External(url))
        .title("Ragnarok Offline")
        .inner_size(1280.0, 800.0)
        .resizable(true)
        .build()
        .map_err(|e| e.to_string())?;
    Ok(())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(AppState::default())
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![
            stack_status,
            stack_up,
            stack_down,
            assets_ready,
            assets_start,
            assets_stop,
            get_settings,
            save_settings,
            open_game
        ])
        .run(tauri::generate_context!())
        .expect("error while running RagnarokMac");
}
