use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::Mutex;

use serde::{Deserialize, Serialize};
use tauri::menu::{Menu, MenuItem, PredefinedMenuItem, Submenu};
use tauri::{Manager, WebviewUrl, WebviewWindowBuilder};

/// The game window boots into src/index.html and is then navigated here. The
/// jump has to happen from Rust: the boot page is served from `tauri://localhost`,
/// a secure origin, so it can neither fetch nor be trusted to navigate to a
/// plain-http origin from script.
///
/// roBrowser's own app page, loaded directly rather than embedded with
/// ROBrowser.TYPE.FRAME. The frame variant nests the game in an iframe, which
/// takes keyboard focus away from it — no chat input, no movement keys — and
/// buys nothing when the game already fills the window. Settings come from
/// Config.local.js, which this page merges over Config.js.
const GAME_URL: &str = "http://127.0.0.1:3338/api.html?app=ONLINE";
const HEALTH_URL: &str = "http://127.0.0.1:3338/api/health";

/// Rates the Settings pane exposes. Values are multipliers in percent, matching
/// rAthena's own units (100 = 1x), so they can be written straight into
/// `conf/import/battle_conf.txt` without translation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Settings {
    pub base_exp_rate: u32,
    pub job_exp_rate: u32,
    pub quest_exp_rate: u32,
    pub item_rate_common: u32,
    pub item_rate_equip: u32,
    pub item_rate_card: u32,
    pub zeny_rate: u32,
    pub atcommand_enabled: bool,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            base_exp_rate: 100,
            job_exp_rate: 100,
            quest_exp_rate: 100,
            item_rate_common: 100,
            item_rate_equip: 100,
            item_rate_card: 100,
            zeny_rate: 100,
            atcommand_enabled: true,
        }
    }
}

impl Settings {
    /// Render to rAthena's import override file. Upstream `conf/battle/*.conf`
    /// is never touched; `conf/import/battle_conf.txt` is read last and wins.
    fn to_battle_conf(&self) -> String {
        format!(
            "// Generated by RagnarokMac. Edits here are overwritten.\n\
             base_exp_rate: {}\n\
             job_exp_rate: {}\n\
             quest_exp_rate: {}\n\
             item_rate_common: {}\n\
             item_rate_common_boss: {}\n\
             item_rate_equip: {}\n\
             item_rate_equip_boss: {}\n\
             item_rate_card: {}\n\
             item_rate_card_boss: {}\n\
             item_rate_heal: {}\n\
             item_rate_use: {}\n\
             zeny_rate: {}\n\
             atcommand_max_level: {}\n",
            self.base_exp_rate,
            self.job_exp_rate,
            self.quest_exp_rate,
            self.item_rate_common,
            self.item_rate_common,
            self.item_rate_equip,
            self.item_rate_equip,
            self.item_rate_card,
            self.item_rate_card,
            self.item_rate_common,
            self.item_rate_common,
            self.zeny_rate,
            if self.atcommand_enabled { 99 } else { 100 },
        )
    }
}

/// Where the user's Ragnarok client lives. Persisted in the standard macOS
/// application-support directory so it survives reinstalls of the app, and so
/// nothing about the user's filesystem is baked into the build.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ClientPaths {
    pub data_grf: String,
    pub rdata_grf: String,
    /// The ROenglishRE overlay. Optional — without it the game runs, it just
    /// loses the costume and effect art that overlay provides.
    #[serde(default)]
    pub official_grf: String,
}

impl ClientPaths {
    fn complete(&self) -> bool {
        !self.data_grf.is_empty()
            && !self.rdata_grf.is_empty()
            && Path::new(&self.data_grf).is_file()
            && Path::new(&self.rdata_grf).is_file()
    }
}

#[derive(Default)]
struct AppState {
    assets: Mutex<Option<Child>>,
}

/// Everything the app needs at runtime, in a writable location.
///
/// The bundled payload lives in Contents/Resources, which must be treated as
/// read-only — a signed bundle cannot be written to without breaking its
/// signature, and the asset server needs to write symlinks, DATA.INI and a
/// generated client config. So the payload is materialised once into
/// Application Support and used from there. APFS clones make the copy nearly
/// free; it falls back to a plain recursive copy elsewhere.
fn runtime_root(app: &tauri::AppHandle) -> PathBuf {
    if let Ok(dir) = std::env::var("RAGNAROKMAC_ROOT") {
        return PathBuf::from(dir);
    }

    let bundled = app.path().resource_dir().ok().map(|r| r.join("payload"));
    let installed = app
        .path()
        .app_data_dir()
        .map(|d| d.join("runtime"))
        .unwrap_or_default();

    if let Some(payload) = bundled.filter(|p| p.join("scripts/stack.sh").exists()) {
        let want = std::fs::read_to_string(payload.join("VERSION")).unwrap_or_default();
        let have = std::fs::read_to_string(installed.join("VERSION")).unwrap_or_default();
        if want != have || !installed.join("scripts/stack.sh").exists() {
            let _ = std::fs::remove_dir_all(&installed);
            if let Some(parent) = installed.parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            // -c asks for APFS clones: no data is duplicated on disk.
            let ok = Command::new("cp")
                .args(["-Rc", &payload.to_string_lossy(), &installed.to_string_lossy()])
                .status()
                .map(|s| s.success())
                .unwrap_or(false)
                || Command::new("cp")
                    .args(["-R", &payload.to_string_lossy(), &installed.to_string_lossy()])
                    .status()
                    .map(|s| s.success())
                    .unwrap_or(false);
            if !ok {
                return payload;
            }
        }
        return installed;
    }

    // Running from a checkout (cargo tauri dev / a dev build).
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_default()
}

fn project_root(app: &tauri::AppHandle) -> PathBuf {
    runtime_root(app)
}

/// Generated conf, the imported schema and the merged System directory. Kept
/// out of runtime/ so an app update, which replaces runtime/ wholesale, does
/// not discard it.
fn state_dir(app: &tauri::AppHandle) -> PathBuf {
    if let Ok(dir) = std::env::var("RAGNAROKMAC_STATE") {
        return PathBuf::from(dir);
    }
    match app.path().app_data_dir() {
        Ok(d) => d.join("state"),
        Err(_) => project_root(app).join(".ragnarokmac"),
    }
}

/// ~/Library/Application Support/com.ragnarokmac.app/client.json
fn client_config_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("no application data directory: {e}"))?;
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir.join("client.json"))
}

#[tauri::command]
fn get_client_paths(app: tauri::AppHandle) -> ClientPaths {
    client_config_path(&app)
        .ok()
        .and_then(|p| std::fs::read_to_string(p).ok())
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default()
}

#[tauri::command]
fn client_ready(app: tauri::AppHandle) -> bool {
    get_client_paths(app).complete()
}

/// Save the chosen client and symlink it into the asset server. The GRFs are
/// never copied — a full client is gigabytes and stays where the user put it.
#[tauri::command]
fn set_client_paths(app: tauri::AppHandle, paths: ClientPaths) -> Result<String, String> {
    if !Path::new(&paths.data_grf).is_file() {
        return Err("data.grf is not a file".into());
    }
    if !Path::new(&paths.rdata_grf).is_file() {
        return Err("rdata.grf is not a file".into());
    }
    std::fs::write(
        client_config_path(&app)?,
        serde_json::to_string_pretty(&paths).map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;

    let root = project_root(&app);
    let mut cmd = Command::new("bash");
    cmd.arg(root.join("scripts/link-assets.sh"))
        .arg(&paths.data_grf)
        .arg(&paths.rdata_grf);
    if !paths.official_grf.is_empty() {
        cmd.arg(&paths.official_grf);
    }
    let out = cmd
        .current_dir(&root)
        .env("PATH", tool_path())
        .env("RAGNAROKMAC_STATE", state_dir(&app))
        .output()
        .map_err(|e| format!("failed to link assets: {e}"))?;
    if !out.status.success() {
        return Err(String::from_utf8_lossy(&out.stderr).to_string());
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

/// First-run window: asks for the client, then hands off to the game.
#[tauri::command]
fn open_setup(app: tauri::AppHandle) -> Result<(), String> {
    if let Some(win) = app.get_webview_window("setup") {
        let _ = win.show();
        let _ = win.set_focus();
        return Ok(());
    }
    WebviewWindowBuilder::new(&app, "setup", WebviewUrl::App("setup.html".into()))
        .title("Set up your client")
        .inner_size(620.0, 560.0)
        .resizable(false)
        .center()
        .build()
        .map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
fn close_setup(app: tauri::AppHandle) {
    if let Some(win) = app.get_webview_window("setup") {
        let _ = win.close();
    }
}

/// Finder-launched apps inherit launchd's minimal PATH, so nothing installed by
/// Homebrew, Rancher Desktop or Docker Desktop is visible. Every tool we shell
/// out to lives in one of these.
fn tool_path() -> String {
    let home = std::env::var("HOME").unwrap_or_default();
    let existing = std::env::var("PATH").unwrap_or_default();
    format!("{home}/.rd/bin:/opt/homebrew/bin:/usr/local/bin:/opt/podman/bin:{existing}")
}

/// Absolute path of a tool: the copy we ship first, then the usual locations.
fn find_tool(app: &tauri::AppHandle, name: &str) -> Option<PathBuf> {
    let bundled = project_root(app).join("bin").join(name);
    if bundled.is_file() {
        return Some(bundled);
    }
    for dir in tool_path().split(':').filter(|d| !d.is_empty()) {
        let candidate = Path::new(dir).join(name);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

fn run_stack(app: &tauri::AppHandle, arg: &str) -> Result<String, String> {
    let root = project_root(app);
    let out = Command::new("bash")
        .arg(root.join("scripts/stack.sh"))
        .arg(arg)
        .current_dir(&root)
        .env("PATH", tool_path())
        .env("NEBULA_BIN", root.join("bin/nebula"))
        .env("RAGNAROKMAC_DOCKER", root.join("bin/docker-slim"))
        .env("RAGNAROKMAC_STATE", state_dir(app))
        .output()
        .map_err(|e| format!("failed to run stack.sh: {e}"))?;
    let stdout = String::from_utf8_lossy(&out.stdout).to_string();
    if out.status.success() {
        Ok(stdout)
    } else {
        Err(format!(
            "{stdout}{}",
            String::from_utf8_lossy(&out.stderr)
        ))
    }
}

#[tauri::command]
fn stack_status(app: tauri::AppHandle) -> Result<String, String> {
    run_stack(&app, "status")
}

#[tauri::command]
fn stack_up(app: tauri::AppHandle) -> Result<String, String> {
    run_stack(&app, "up")
}

#[tauri::command]
fn stack_down(app: tauri::AppHandle) -> Result<String, String> {
    run_stack(&app, "down")
}

/// True once the RemoteClient-JS unified server answers its health endpoint.
#[tauri::command]
fn assets_ready() -> bool {
    Command::new("curl")
        .args(["-sf", "-m", "2", "-o", "/dev/null", HEALTH_URL])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

#[tauri::command]
fn assets_start(app: tauri::AppHandle, state: tauri::State<'_, AppState>) -> Result<(), String> {
    if assets_ready() {
        return Ok(());
    }
    let dir = project_root(&app).join("vendor/roBrowserLegacy-RemoteClient-JS");
    let node = find_tool(&app, "node")
        .ok_or_else(|| "node was not found (no bundled copy and none installed)".to_string())?;
    let child = Command::new(node)
        .arg("index.js")
        .current_dir(&dir)
        .env("PATH", tool_path())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| format!("failed to start asset server: {e}"))?;
    *state.assets.lock().unwrap() = Some(child);
    Ok(())
}

#[tauri::command]
fn assets_stop(state: tauri::State<'_, AppState>) {
    if let Some(mut child) = state.assets.lock().unwrap().take() {
        let _ = child.kill();
        return;
    }
    // We adopt an already-running server rather than starting a second one, so
    // on the way out there may be nothing to kill by handle. Fall back to
    // whatever holds our port — the app owns 3338 either way.
    if let Ok(out) = Command::new("lsof")
        .args(["-ti", "tcp:3338", "-sTCP:LISTEN"])
        .output()
    {
        for pid in String::from_utf8_lossy(&out.stdout).split_whitespace() {
            let _ = Command::new("kill").arg(pid).status();
        }
    }
}

#[tauri::command]
fn get_settings(app: tauri::AppHandle) -> Settings {
    let path = project_root(&app).join(".ragnarokmac/settings.json");
    std::fs::read_to_string(path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default()
}

/// Persist the rates and re-render the rAthena override file. The map server is
/// restarted because several of these are only read at map-server startup.
#[tauri::command]
fn save_settings(app: tauri::AppHandle, settings: Settings) -> Result<String, String> {
    let root = project_root(&app);
    let state_dir = root.join(".ragnarokmac");
    std::fs::create_dir_all(state_dir.join("conf")).map_err(|e| e.to_string())?;
    std::fs::write(
        state_dir.join("settings.json"),
        serde_json::to_string_pretty(&settings).map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;
    std::fs::write(
        state_dir.join("conf/battle_conf.txt"),
        settings.to_battle_conf(),
    )
    .map_err(|e| e.to_string())?;
    run_stack(&app, "up")
}

/// Bring the game window back, reloading it from the boot page so it retries the
/// startup sequence if the server was restarted underneath it.
#[tauri::command]
fn open_game(app: tauri::AppHandle) -> Result<(), String> {
    if let Some(win) = app.get_webview_window("game") {
        let _ = win.navigate("tauri://localhost/index.html".parse().unwrap());
        let _ = win.show();
        let _ = win.set_focus();
        return Ok(());
    }
    WebviewWindowBuilder::new(&app, "game", WebviewUrl::App("index.html".into()))
        .title("Ragnarok Offline")
        .inner_size(1280.0, 800.0)
        .build()
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// Point the game window at the running client. Called by the boot page once
/// `assets_ready` reports the server is answering.
#[tauri::command]
fn launch_game(app: tauri::AppHandle) -> Result<(), String> {
    let win = app
        .get_webview_window("game")
        .ok_or_else(|| "game window is gone".to_string())?;
    let url = GAME_URL.parse().map_err(|_| "bad game url".to_string())?;
    win.navigate(url).map_err(|e| e.to_string())?;
    Ok(())
}

/// Settings is a secondary window: ⌘, or the app menu, never the launch surface.
#[tauri::command]
fn open_settings(app: tauri::AppHandle) -> Result<(), String> {
    if let Some(win) = app.get_webview_window("settings") {
        let _ = win.show();
        let _ = win.set_focus();
        return Ok(());
    }
    WebviewWindowBuilder::new(&app, "settings", WebviewUrl::App("settings.html".into()))
        .title("Settings")
        .inner_size(560.0, 720.0)
        .resizable(true)
        .build()
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// One call for "make the game playable": bring the containers up, then the
/// asset server, in that order — the WebSocket proxy only reads its allowlist
/// at startup.
#[tauri::command]
fn start_stack(app: tauri::AppHandle, state: tauri::State<'_, AppState>) -> Result<String, String> {
    // Re-link the client every start. It is idempotent, and a freshly
    // materialised runtime (first launch, or after an app update) has no GRF
    // symlinks or DATA.INI in it yet — only the setup window writes those, and
    // it is skipped once a client is remembered.
    let saved = get_client_paths(app.clone());
    if saved.complete() {
        set_client_paths(app.clone(), saved)?;
    }
    let out = run_stack(&app, "up")?;
    assets_start(app, state)?;
    Ok(out)
}

fn build_menu(app: &tauri::AppHandle) -> tauri::Result<Menu<tauri::Wry>> {
    let settings = MenuItem::with_id(app, "settings", "Settings…", true, Some("CmdOrCtrl+,"))?;
    // On macOS the first submenu becomes the application menu, which is where
    // Settings belongs. Elsewhere this reads as the File menu.
    let app_menu = Submenu::with_items(
        app,
        "RagnarokMac",
        true,
        &[
            &settings,
            &PredefinedMenuItem::separator(app)?,
            &PredefinedMenuItem::hide(app, None)?,
            &PredefinedMenuItem::separator(app)?,
            &PredefinedMenuItem::quit(app, None)?,
        ],
    )?;
    let edit = Submenu::with_items(
        app,
        "Edit",
        true,
        &[
            &PredefinedMenuItem::undo(app, None)?,
            &PredefinedMenuItem::redo(app, None)?,
            &PredefinedMenuItem::separator(app)?,
            &PredefinedMenuItem::cut(app, None)?,
            &PredefinedMenuItem::copy(app, None)?,
            &PredefinedMenuItem::paste(app, None)?,
            &PredefinedMenuItem::select_all(app, None)?,
        ],
    )?;
    let window = Submenu::with_items(
        app,
        "Window",
        true,
        &[
            &PredefinedMenuItem::minimize(app, None)?,
            &PredefinedMenuItem::fullscreen(app, None)?,
            &PredefinedMenuItem::close_window(app, None)?,
        ],
    )?;
    Menu::with_items(app, &[&app_menu, &edit, &window])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(AppState::default())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .setup(|app| {
            let handle = app.handle();
            handle.set_menu(build_menu(handle)?)?;

            // A signal terminates the process without an ExitRequested event,
            // so `kill`, a logout, or Ctrl-C would otherwise leave the whole
            // stack running. Same teardown as a clean quit.
            let signal_handle = handle.clone();
            std::thread::spawn(move || {
                use signal_hook::consts::{SIGINT, SIGTERM};
                use signal_hook::iterator::Signals;
                let Ok(mut signals) = Signals::new([SIGTERM, SIGINT]) else {
                    return;
                };
                if signals.forever().next().is_some() {
                    if let Some(state) = signal_handle.try_state::<AppState>() {
                        assets_stop(state);
                    }
                    let _ = run_stack(&signal_handle, "down");
                    std::process::exit(0);
                }
            });
            Ok(())
        })
        .on_menu_event(|app, event| {
            if event.id() == "settings" {
                let _ = open_settings(app.clone());
            }
        })
        .invoke_handler(tauri::generate_handler![
            stack_status,
            stack_up,
            stack_down,
            start_stack,
            assets_ready,
            assets_start,
            assets_stop,
            get_settings,
            save_settings,
            open_game,
            open_settings,
            launch_game,
            get_client_paths,
            set_client_paths,
            client_ready,
            open_setup,
            close_setup
        ])
        .build(tauri::generate_context!())
        .expect("error while building RagnarokMac")
        .run(|app, event| {
            // Quitting the game should not leave a database and three game
            // servers running for the rest of the session. The DB lives in a
            // named volume, so nothing is lost by stopping them.
            if let tauri::RunEvent::ExitRequested { .. } = event {
                if let Some(state) = app.try_state::<AppState>() {
                    assets_stop(state);
                }
                let _ = run_stack(app, "down");
            }
        });
}
