-- A ready-to-use login for a fresh install.
--
-- Without this the first thing a new player meets is rAthena's registration
-- convention: type your username with an _M or _F suffix and the account is
-- created implicitly. That is fine once you know it and baffling when you do
-- not, and nothing on the login screen says so.
--
-- group_id 99 is the Admin group from conf/groups.yml. This is a single-player
-- server on loopback that the player also operates, so @commands work out of
-- the box. To play without them: UPDATE login SET group_id = 0 WHERE userid =
-- 'ragnarok';
--
-- Passwords are plaintext because rAthena's use_MD5_passwords defaults to no
-- and we do not override it -- the same as the s1/p1 row the schema ships.
--
-- No character is created: the player picks their own class and appearance.
--
-- Guarded with NOT EXISTS rather than INSERT IGNORE: rAthena indexes userid
-- with a plain KEY, not a UNIQUE one, so IGNORE has no conflict to suppress and
-- happily inserts a second 'ragnarok' every startup.
--
-- The birthdate is 2000-01-01 rather than the NULL the schema defaults to,
-- because it is what lets a player delete a character. rAthena asks the client
-- for the account's birthday and compares it to this column
-- (chclif_delchar_check in src/char/char_clif.cpp), and nothing else in this
-- app ever writes it. A NULL one cannot be matched: the sole value that would
-- pass is an empty birthday, and roBrowser's input box will not submit an empty
-- field, so the delete prompt refuses everything the player can type. The same
-- date is written by account creation in stack/src/accounts.rs, and by the
-- Accounts panel's migration for databases seeded before this line existed.
INSERT INTO `login` (`userid`, `user_pass`, `sex`, `email`, `group_id`, `birthdate`)
SELECT 'ragnarok', 'ragnarok', 'M', 'ragnarok@localhost', 99, '2000-01-01' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM `login` WHERE `userid` = 'ragnarok');
